### ISSUE TITLE
run_unit_tests.py script improvements

### ISSUE THREAD

**Issue by timothy22000** [osirixgrpc/osirixgrpc#12]
- Ensure that the user's machine has Git installed as the script requires it to clone the osirixgrpc repository
- Create the required "osirixgrpc_tests" folder on the user's machine which is required to store the test outputs

Possibly a note to mention about deleting the "Test Patients" database in Osirix if they are running it again

**Comment by mdblackledge** [comment]
Ability to check for output directory now added as of dev72.
