### ISSUE TITLE
link to latest release shows error 404

### ISSUE THREAD

**Issue by derlinuslinus** [osirixgrpc/osirixgrpc#13]
Hi,
I am very interested in using your osirix plugin for AI segmentation. I would like to download the latest release if it is actually released. Until now I cant find the osirixgrpc.osirixplugin file.
I have no experience in coding and am just starting to dig into it...
Looking forward to your answer.

**Comment by mdblackledge** [comment]
Hello!  Thanks for your interest in OsiriXgrpc!  We are due to release a beta  version in the next couple of weeks.  I will update you when it is here and it would be great to get your feedback.

**Comment by derlinuslinus** [comment]
Thanks for the answer! I am looking forward to the release. Most likely I will habe some further questions when really working with it. I hope you stay open for it!
Thanks!

**Comment by mdblackledge** [comment]
Hello!  The software has now been released as beta.  Please see the link here: https://osirixgrpc.github.io/osirixgrpc/getting_started.html

If there are any issues, please do let us know and we will help and/or make bug fixes prior to our release of the first full version in August.

**Comment by mdblackledge** [comment]
Closing this as conversation has moved to https://github.com/osirixgrpc/osirixgrpc/issues/18
