### ISSUE TITLE
Osirixgrpc model cannot be found

### ISSUE THREAD

**Issue by derlinuslinus** [osirixgrpc/osirixgrpc#18]
### Contact Details

linus.grossmann@uni-greifswald.de

### Documentation Scope

OsiriXgrpc

### OsiriXgrpc Version

0.2.1 beta

### What would you like to see?

Hi, thanks for the released beta. I am now trying to dig into the plugin to use it for AI segmentation of the stomach. As I have no experience in coding, I will run into some issues. And the first one is as follows...
![Screenshot 17 06 2024 um 09 35 08 AM](https://github.com/osirixgrpc/osirixgrpc/assets/170704163/7a54246b-aba1-4085-94a0-ed2383408c7d)
It seems that the OsiriXgrpc model cannot be found in the grpcio. Is this due to a wrong python version? What could be the problem? If this is too specific or too easy for this git issue I am looking forward to get in contact with you via mail.
Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdblackledge** [comment]
Thanks! Have you tried running `pip install osirix`?
Also, once you do this, you will not need to set up your own server.  Simply running `install osirix` should do the trick.
See more documentation for using pyOsiriX here: https://osirixgrpc.github.io/osirixgrpc/pyosirix/index.html

**Comment by mdblackledge** [comment]
Hello! I just wanted to touch base and check whether the response above managed to solve your issue?

**Comment by derlinuslinus** [comment]
Yes, thanks, that helped! If there are any other problems I will open another issue.
