### ISSUE TITLE
Build.sh improvements

### ISSUE THREAD

**Issue by timothy22000** [osirixgrpc/osirixgrpc#5]
- Add line to install cmake in build.sh

**Comment by mdblackledge** [comment]
Agree.  I will make a change and let you know so that it can be tested. Just for clarity, what is the error if you run the script without this?

**Comment by timothy22000** [comment]
This is the error that I received when I ran the script initially without Cmake:

![WhatsApp Image 2024-02-23 at 16 08 49](https://github.com/osirixgrpc/osirixgrpc/assets/9934371/018672dc-9c9c-4926-88c3-efe5a807ad21)
![WhatsApp Image 2024-02-23 at 16 05 43](https://github.com/osirixgrpc/osirixgrpc/assets/9934371/5c76c8a5-dd20-451c-aadf-a8ea550a4679)

**Comment by mdblackledge** [comment]
Added to dev73
